<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Страница не найдена!</h1>
        <div class="row row-cols-1 row-cols-lg-2 align-items-lg-center">
            <div class="col">
                <img class="img-fluid" alt="404 error" src="/assets/404.svg" loading="lazy">
            </div>
            <div class="col">
                <h2 class="h2 mb-4">Ошибка 404</h2>
                <p class="fs-5 text-black mb-3">Что случилось?</p>
                <p class="mb-4">Вы попали на страницу, которой не существует</p>
                <p class="fs-5 text-black mb-3">Почему это произошло?</p>
                <p class="mb-4">В большинстве ситуаций ошибка 404 отображается, если связь с сервером установлена, но информации по заданному запросу нет. Возможно, в адресе опечатка — такое случается при ручном наборе. Или страница была удалена, но сохранилась в закладках вашего браузера</p>
                <p class="fs-5 text-black mb-3">Что делать?</p>
                <p class="mb-2">Поскольку мы не знаем, как и откуда вы попали на эту страницу, то рекомендуем начать <a href="/">с главной</a></p>
            </div>
        </div>
    </div>
</main>