<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Что-то пошло не так!</h1>
        <div class="row row-cols-1 row-cols-lg-2 align-items-lg-center">
            <div class="col">
                <img class="img-fluid" alt="404 error" src="/assets/500.jpg" loading="lazy">
            </div>
            <div class="col">
                <h2 class="h2 mb-4">Ошибка 500</h2>
                <p class="fs-5 text-black mb-3">Что случилось?</p>
                <p class="mb-4">Вы попали на эту страницу, потому что произошла ошибка на сервере</p>
                <p class="fs-5 text-black mb-3">Почему это произошло?</p>
                <p class="mb-4">Потому что у разработчика кривые руки</p>
                <p class="fs-5 text-black mb-3">Что делать?</p>
                <p class="mb-2">Рекомендуем начать <a href="/">с главной</a></p>
            </div>
        </div>
    </div>
</main>