<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <title>Анализатор страниц</title>
</head>
<body>
    <header class="flex-shrink-0">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
            <a class="navbar-brand" href="/">Анализатор страниц</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link <?= $routeName === 'home' ? 'active' : '' ?>" href="/">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link  <?= $routeName === 'showUrl' || $routeName === 'urls' ? 'active' : '' ?>" href="/urls">Сайты</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <?php if (isset($flash)) : ?>
        <?php foreach ($flash as $alert => $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <div class="alert alert-<?= $alert ?>" role="alert"><?= $message ?></div>
            <?php endforeach ?>
        <?php endforeach ?>
    <?php endif ?>

    <?= $content ?>
    <footer class="border-top py-3 mt-5 fixed-bottom">
        <div class="container-lg">
            <div class="text-center">
                <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
            </div>
        </div>
    </footer>
</body>
</html>